version: '3'
services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    restart: always

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./Frontend/.env
    restart: always
